---
#- import_playbook: test.ym
# Install Apache
- hosts: moodle
  become_user: root
  become: yes
  connection: local
  tasks:
  - name: install httpd service
    yum: 
      name: httpd 
      state: latest 
      update_cache: yes
  - name: Download GIT and vim just in case
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
    - git
    - vim
   
  - name: start and enable httpd services
    service: 
      name: httpd 
      state: started 
      enabled: true

  - name: Install MariaDB (MySQL) Server
    yum: 
      name: "{{ item }}" 
      state: latest 
      update_cache: yes
    with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

  - name: start and enable service
    service: 
      name: mariadb 
      state: started 
      enabled: true

  # Remove all anonymous mysql users
  - name: remove test database
    mysql_db: 
      db: test 
      state: absent

  # Set root password on first run
  #- name: Sets the root password on first run
  # mysql_user: 
  #    login_user: root 
  #    login_password: '' 
  #    name: root 
  ##    password: "{{mysql_root_password}}" 
  #    priv: "*.*:ALL, GRANT" 
  #    host: "{{item}}"
  #  with_items:
  #    - vagrant
  ##    - 192.168.0.93
  #    - ::1
  #    - localhost

  # Install PHP
 # - name: install php and related modules
  #  yum: 
      #name: "{{item}}" 
     # state: latest 
    #  update_cache: yes
   # with_items:
  #  - php
 #   - php-mysql 
#    - php-gd
  - name: all the git stuff
    git:
     repo: "git://github.com/moodle/moodle.git"
     dest: /var/www/html
